### PR TITLE
Add the link editor plugin

### PR DESCRIPTION
**Pull request by brichet**
This PR adds the skeleton of a link editor plugin.

### CODE REVIEW

**Comment by trungleduc** [comment]
Thanks @brichet for starting it, since the binder link does not work yet, could you add some screenshots?

**Comment by brichet** [comment]
This adds a empty panel when clicking on one of the `link` button from control panels, and also add a command to the palette.

Peek 2023-03-31 12-19

**Comment by trungleduc** [comment]
Great! Since the link editor can be opened without opening a session file, how can it get the list of datasets to be linked?

**Comment by brichet** [comment]
Thanks @trungleduc, I hadn't included it in this first PR but you're right, let's do it properly.

Does this data should be in the `GlueSessionSharedModel` of the tracker ?
If so, we could expect this `GlueSessionSharedModel` to be defined.

**Comment by trungleduc** [comment]
Yes, but if there is no session file opened, this model will be undefined. I start thinking that we should only open the link editor from the `glue-lab` interface so that we can be sure that we have access to this model.

**Comment by trungleduc** [comment]
Another point of the design, do we want to have the link editor view at the same level as the session file, to me, it is a sub-dialog of the currently opened session, like in the current glue QT app

glue2

**Comment by brichet** [comment]
> I start thinking that we should only open the link editor from the `glue-lab` interface so that we can be sure that we have access to this model.

We can enable the command form the palette only if a session is opened.

**Comment by brichet** [comment]
Closing it as not relevant anymore:
- link editor will be a tab for each session's view
- no link button is necessary

**Pull request closed without merging**
