### PR TITLE
Fix widget state parser

### PR DESCRIPTION
**Pull request by trungleduc**

### CODE REVIEW

**Review by brichet — COMMENTED** [review]
Thanks @trungleduc, that fixes the blank viewer and the kernel error.
Nevertheless that raise some error on glue when data is None:
```
Traceback (most recent call last):
  File "/home/brichet/mambaforge/envs/glue/lib/python3.10/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/brichet/mambaforge/envs/glue/lib/python3.10/site-packages/glue_jupyter/utils.py", line 119, in debounced_execute
    f(*args, **kwargs)
  File "/home/brichet/mambaforge/envs/glue/lib/python3.10/site-packages/glue_jupyter/bqplot/scatter/layer_artist.py", line 156, in update_histogram
    self.counts = data.compute_histogram([self._viewer_state.x_att,
  File "/home/brichet/mambaforge/envs/glue/lib/python3.10/site-packages/glue/core/data.py", line 1908, in compute_histogram
    x = self.get_data(cids[0])
  File "/home/brichet/mambaforge/envs/glue/lib/python3.10/site-packages/glue/core/data.py", line 1413, in get_data
    raise IncompatibleAttribute(cid)
glue.core.exceptions.IncompatibleAttribute: None
```
Maybe we should remove the viewer when the data is not consistent, or display a message in the viewer.

**Comment by trungleduc** [comment]
It's weird, from the docstring of these functions, `data` is optional but it is not handled properly.

```
        data : str or `~glue.core.data.Data`, optional
            The initial dataset to show in the viewer. Additional
            datasets can be added later using the ``add_data`` method on
            the viewer object.
```

**Review by brichet — APPROVED** [review]

**Comment by trungleduc** [comment]
Ok so the issue does not relate to the input data, but in the state of the widget. The `x_att`  and `y_att` of a widget state are  `None` and it's passed to this function https://github.com/glue-viz/glue-jupyter/blob/ebc2ed67bb6e6714b22d861c11f0b2f470e3e21c/glue_jupyter/bqplot/scatter/layer_artist.py#L156

**Comment by brichet** [comment]
> Ok so the issue does not relate to the input data, but in the state of the widget. The `x_att` and `y_att` of a widget state are `None` and it's passed to this function https://github.com/glue-viz/glue-jupyter/blob/ebc2ed67bb6e6714b22d861c11f0b2f470e3e21c/glue_jupyter/bqplot/scatter/layer_artist.py#L156

Same error on my side with the latest modification, and there is another one about `ZeroDivisionError`, possibly related to empty data.

**Comment by trungleduc** [comment]
> > Ok so the issue does not relate to the input data, but in the state of the widget. The `x_att` and `y_att` of a widget state are `None` and it's passed to this function https://github.com/glue-viz/glue-jupyter/blob/ebc2ed67bb6e6714b22d861c11f0b2f470e3e21c/glue_jupyter/bqplot/scatter/layer_artist.py#L156
> 
> Same error on my side with the latest modification, and there is another one about `ZeroDivisionError`, possibly related to empty data.

It's normal, the latest changes do not fix the error message because it's an issue with the glue session file or glue core implementation, not glue-lab. I think it's the same for the `bqplot` error on `ZeroDivisionError`.

**Comment by brichet** [comment]
Thanks @trungleduc

**Pull request merged**
